# Generated by Django 5.1.5 on 2025-01-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingForgotPasswordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=255)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
