# Generated by Django 5.1.5 on 2025-02-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='local_ip',
            field=models.CharField(default='0.0.0.0', max_length=25),
        ),
    ]
