# Generated by Django 5.1.5 on 2025-03-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_local_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='devices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
