# Generated by Django 5.1.5 on 2025-03-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='devices',
        ),
        migrations.AddField(
            model_name='user',
            name='locl_wifi',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
