# Generated by Django 5.1.5 on 2025-03-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_devices_user_locl_wifi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locl_wifi',
            field=models.CharField(default='No wifi', max_length=255),
        ),
    ]
