# Generated by Django 5.1.5 on 2025-03-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_user_locl_wifi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='local_wifi',
            field=models.CharField(default='No WiFi', max_length=255),
        ),
    ]
