# Generated by Django 5.1.5 on 2025-04-05 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_balcony_user_bedroom1_user_bedroom2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bedroom1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bedroom2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bedroom3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='corridor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dining',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='user',
            name='living_room',
        ),
    ]
