# Generated by Django 5.1.5 on 2025-01-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pin1_state', models.BooleanField(default=False)),
                ('pin2_state', models.BooleanField(default=False)),
                ('pin3_state', models.BooleanField(default=False)),
                ('pin4_state', models.BooleanField(default=False)),
                ('pin5_state', models.BooleanField(default=False)),
                ('pin6_state', models.BooleanField(default=False)),
                ('pin7_state', models.BooleanField(default=False)),
                ('pin8_state', models.BooleanField(default=False)),
            ],
        ),
    ]
