# Generated by Django 5.1.5 on 2025-02-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_pin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='pin1_state',
            new_name='pin_1',
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='pin2_state',
            new_name='pin_2',
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='pin3_state',
            new_name='pin_3',
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='pin4_state',
            new_name='pin_4',
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='pin5_state',
            new_name='pin_5',
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='pin6_state',
            new_name='pin_6',
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='pin7_state',
            new_name='pin_7',
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='pin8_state',
            new_name='pin_8',
        ),
    ]
