# Generated by Django 5.1.5 on 2025-02-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_pin', '0002_rename_pin1_state_pin_pin_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='pin_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='pwm_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pin',
            name='pwm_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pin',
            name='pwm_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pin',
            name='pwm_4',
            field=models.IntegerField(default=0),
        ),
    ]
