# Generated by Django 5.1.5 on 2025-02-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_pin', '0003_pin_pin_10_pin_pin_11_pin_pin_12_pin_pin_13_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
