# Generated by Django 5.1.5 on 2025-04-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_pin', '0006_pin_balcony_pin_bedroom1_pin_bedroom2_pin_bedroom3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='pin_10_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_10_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_11_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_11_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_12_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_12_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_13_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_13_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_14_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_14_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_15_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_15_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_16_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_16_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_1_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_1_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_2_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_2_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_3_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_3_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_4_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_4_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_5_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_5_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_6_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_6_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_7_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_7_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_8_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_8_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_9_subTitle',
            field=models.CharField(default='Just a switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_9_title',
            field=models.CharField(default='switch', max_length=255),
        ),
        migrations.AddField(
            model_name='pin',
            name='used_pin_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
