# Generated by Django 5.1.5 on 2025-04-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_pin', '0007_pin_pin_10_subtitle_pin_pin_10_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin_10_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_11_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_12_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_13_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_14_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_15_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_16_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_1_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_2_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_3_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_4_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_5_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_6_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_7_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_8_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_9_title',
            field=models.CharField(default='Switch', max_length=255),
        ),
    ]
