# Generated by Django 5.1.5 on 2025-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_pin', '0008_alter_pin_pin_10_title_alter_pin_pin_11_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='pin_10_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_10_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_11_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_11_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_12_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_12_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_13_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_13_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_14_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_14_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_15_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_15_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_16_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_16_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_1_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_1_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_2_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_2_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_3_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_3_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_4_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_4_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_5_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_5_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_6_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_6_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_7_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_7_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_8_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_8_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_9_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_9_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
